name: Build and deploy ASP.Net Core app to Azure Web App - reciclafuturo

on:
  push:
    branches:
      - Develop
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ReciclaFuturo/ReciclaFuturo.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ReciclaFuturo/ReciclaFuturo.csproj -c Release -o myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Isso é necessário para a autenticação de identidade gerenciada

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure with Managed Identity
        uses: azure/login@v2
        with:
          managed-identity-client-id: bddc8f02-d1bc-494a-ab40-0b57efa868b2  # Use o Object ID da Identidade Gerenciada
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'reciclafuturo'
          slot-name: 'production'
          package: myapp
